### ISSUE TITLE
"import" functionality is not working

### ISSUE THREAD

**Issue by kvyas248** [hashicorp/terraform-provider-hashicups#11]
We are trying to develop a custom terraform provider which can support terraform import. While learning to do that we are trying to add import order functionality to terraform-provider-hashicups for orders api. I am unable to find any tutorial for import functionality with terraform-plugin-sdk/v2. 

We are following the doc https://www.terraform.io/docs/extend/resources/import.html for adding import functionality for hashicups provider. But it looks like the doc is for V1 and not V2 version of the terraform provider sdk. 

We are adding following code to the datasourcereorder :
	`	Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
	  	},
`

And have added following block to the coffee/main.tf file:

`resource "hashicups_order" "test" {
  id = 1
}`

By trying following command: 
`terraform import module.psl.hashicups_orders.test 1`
we get error saying "Error: Invalid resource type"

Please help us fixing the import functionality.

**Comment by im2nguyen** [comment]
Hi @kvyas248, 

I just added the [`implement-import`](https://github.com/hashicorp/terraform-provider-hashicups/tree/implement-import) branch today. It implements a very simple import using `schema.ImportStatePassthrough` to the [HashiCups order resource](https://github.com/hashicorp/terraform-provider-hashicups/blob/implement-import/hashicups/resource_order.go#L71-L73) and provides an example.

Please let me know if you have any questions about the implementation, the replication steps below and/or specific questions about terraform import.

--- 

I was able to successfully test out the example provided in `/examples/import` by:
1. Creating a HashiCups account and exporting the auth token (instructions [here](https://learn.hashicorp.com/tutorials/terraform/provider-use?in=terraform/providers#create-new-hashicups-user)
1. Creating a new HashiCups order 
  `curl -X POST -H "Authorization: ${HASHICUPS_TOKEN}" localhost:19090/orders -d '[{"coffee": { "id":1 }, "quantity":4}, {"coffee": { "id":3 }, "quantity":3}]'`
1. In the `/examples/import` directory, run the import command.
  `$ terraform import hashicups_order.first 1`

<details>
<summary>Output</summary>
<pre>
hashicups_order.first: Importing from ID "1"...
hashicups_order.first: Import prepared!
  Prepared hashicups_order for import
hashicups_order.first: Refreshing state... [id=1]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
</pre>
</details>

4. Verify that order was imported and saved to state
  `$ terraform state show hashicups_order.first `

<details>
<summary>Output</summary>
<pre>
# hashicups_order.first:
resource "hashicups_order" "first" {
    id = "1"

    items {
        quantity = 4

        coffee {
            id     = 1
            image  = "/packer.png"
            name   = "Packer Spiced Latte"
            price  = 350
            teaser = "Packed with goodness to spice up your images"
        }
    }
    items {
        quantity = 3

        coffee {
            id     = 3
            image  = "/nomad.png"
            name   = "Nomadicano"
            price  = 150
            teaser = "Drink one today and you will want to schedule another"
        }
    }
}
</pre>
</details>

5. Replace the original `hashicups_order.first` resource with the output. Prune resource's attributes (remove computed attributes, etc..).
<details>
<summary>Final hashicups_order.first configuration</summary>
<pre>
# hashicups_order.first:
resource "hashicups_order" "first" {
  items {
    quantity = 4

    coffee {
      id     = 1
    }
  }
  items {
    quantity = 3

    coffee {
      id     = 3
    }
  }
}
</pre>
</details>

6. Apply configuration to view data. There should be no changes and display the full state of `hashicups_order.first`
  `$ terraform apply`
<details>
<summary>Output</summary>
<pre>
hashicups_order.first: Refreshing state... [id=1]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:

Terraform will perform the following actions:

Plan: 0 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + first_order = {
      + id           = "1"
      + items        = [
          + {
              + coffee   = [
                  + {
                      + description = ""
                      + id          = 1
                      + image       = "/packer.png"
                      + name        = "Packer Spiced Latte"
                      + price       = 350
                      + teaser      = "Packed with goodness to spice up your images"
                    },
                ]
              + quantity = 4
            },
          + {
              + coffee   = [
                  + {
                      + description = ""
                      + id          = 3
                      + image       = "/nomad.png"
                      + name        = "Nomadicano"
                      + price       = 150
                      + teaser      = "Drink one today and you will want to schedule another"
                    },
                ]
              + quantity = 3
            },
        ]
      + last_updated = null
    }

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes


Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

first_order = {
  "id" = "1"
  "items" = [
    {
      "coffee" = [
        {
          "description" = ""
          "id" = 1
          "image" = "/packer.png"
          "name" = "Packer Spiced Latte"
          "price" = 350
          "teaser" = "Packed with goodness to spice up your images"
        },
      ]
      "quantity" = 4
    },
    {
      "coffee" = [
        {
          "description" = ""
          "id" = 3
          "image" = "/nomad.png"
          "name" = "Nomadicano"
          "price" = 150
          "teaser" = "Drink one today and you will want to schedule another"
        },
      ]
      "quantity" = 3
    },
  ]
}
</pre>
</details>

**Comment by kvyas248** [comment]
ok. It is working with resources.
