### ISSUE TITLE
Executable from curl command is invalid plugin format for Mac (Terraform Provider tutorial)

### ISSUE THREAD

**Issue by Rickyf115** [hashicorp/terraform-provider-hashicups#14]
Hi there,

The executable being downloaded from the curl command, either gets malformed when unzipped, or the curl command on the tutorial is linking to the incorrect executable. 

This is an issue with this tutorial step:
- https://learn.hashicorp.com/tutorials/terraform/provider-use?in=terraform/providers#install-hashicups-provider

### Terraform Version
13.5

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    hashicups = {
      versions = ["0.2"]
      source   = "hashicorp.com/edu/hashicups"
    }
  }
}

provider "hashicups" {
  username = "education"
  password = "test123"
}

resource "hashicups_order" "edu" {
  items {
    coffee {
      id = 3
    }
    quantity = 2
  }
  items {
    coffee {
      id = 2
    }
    quantity = 2
  }
}

output "edu_order" {
  value = hashicups_order.edu
}
```

### Debug Output
https://gist.github.com/f83731f19d5b7f5074f31fe18267edea

### Expected Behavior
Properly apply terraform state changes to the tfstate file.

### Actual Behavior
Error on apply (Failure to load plugin)

### Steps to Reproduce
1. 'curl -Lo terraform-provider-hashicups https://github.com/hashicorp/terraform-provider-hashicups/releases/download/v0.2.0/terraform-provider-hashicups_0.2.0_darwin_amd64.zip'
2. 'chmod +x terraform-provider-hashicups'
3. 'mkdir -p ~/.terraform.d/plugins/hashicorp.com/edu/hashicups/0.2.0/darwin_amd64'
4. 'mv terraform-provider-hashicups ~/.terraform.d/plugins/hashicorp.com/edu/hashicups/0.2.0/darwin_amd64'
5. 'terraform init'
6. 'terraform plan'

### Workaround

I was able to fix the issue by downloading the executable from this link:

- https://github.com/hashicorp/terraform-provider-hashicups/releases/download/v0.2.0/terraform-provider-hashicups_0.2.0_darwin_amd64.zip

Unzipping with Archive Utility, and moving the executable to the '~/.terraform.d/plugins/hashicorp.com/edu/hashicups/0.2.0/darwin_amd64' directory and renaming it to <b>'terraform-provider-hashicups'</b>

**Comment by im2nguyen** [comment]
Thanks for the catch, will update the tutorial now.

The GitHub link takes you to a redirect instead of the actual file... I uploaded the actual binaries to the release 😄
