### ISSUE TITLE
 Error: Incompatible provider version

### ISSUE THREAD

**Issue by raymondseah** [hashicorp/terraform-provider-hashicups#25]
Hi there,

Was attemping the tutorial to try some hands on.
Just to check if this error is due to the Mac M1 Chip?

│ Error: Incompatible provider version
│ 
│ Provider hashicorp.com/edu/hashicups v0.3.1 does not have a package available for your current platform, darwin_arm64.

Regards
Raymond

**Comment by hermannolafs** [comment]
had that issue also, this should fix it https://github.com/hashicorp/terraform-provider-hashicups/pull/51
