### ISSUE TITLE
It is not clear how to use a local provider with Terraform 0.13

### ISSUE THREAD

**Issue by remilapeyre** [hashicorp/terraform-provider-hashicups#3]
`terraform init` exit with an error when running the commands in the README because it tries to download the provider fro the registry:

```
➜  src cd ~/go/src/github.com/hashicorp 
➜  hashicorp g clone https://github.com/hashicorp/terraform-provider-hashicups
Clonage dans 'terraform-provider-hashicups'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 3073 (delta 8), reused 17 (delta 0), pack-reused 3044
Réception d'objets: 100% (3073/3073), 71.44 Mio | 2.28 Mio/s, fait.
Résolution des deltas: 100% (640/640), fait.
➜  hashicorp cd terraform
➜  terraform git:(consul-split-state) ../terraform-provider-hashicups/
➜  terraform-provider-hashicups git:(master) go build -o terraform-provider-hashicups
go: downloading github.com/hashicorp-demoapp/hashicups-client-go v0.0.0-20200508203820-4c67e90efb8e
go: downloading github.com/hashicorp/terraform-plugin-sdk/v2 v2.0.0-rc.2
go: downloading github.com/hashicorp/go-cty v1.4.1-0.20200414143053-d3edf31b6320
go: downloading github.com/mitchellh/go-testing-interface v1.0.4
➜  terraform-provider-hashicups git:(master) cd examples 
➜  examples git:(master) terraform init && terraform apply
Initializing modules...
- psl in coffee

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/hashicups...

Error: Failed to install provider

Error while installing hashicorp/hashicups: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/hashicups
```

It is not clear how to test a local build of a provider.

**Comment by remilapeyre** [comment]
Apparently it needs to be put at `~/.terraform.d/plugins/registry.terraform.io/hashicorp/hashicups/0.0.1/darwin_amd64/terraform-provider-hashicups_0.0.1`.

**Comment by taiidani** [comment]
The `make install` step has been [hardcoded to a version and OS/architecture](https://github.com/hashicorp/terraform-provider-hashicups/blob/master/Makefile#L28-L30). Which contradicts the `make install` [output from the tutorial](https://learn.hashicorp.com/tutorials/terraform/provider-setup#test-the-provider).

Ref https://github.com/hashicorp/terraform/issues/25862

I'm in the same boat. Having problems trying to locally build my providers without adding a maintenance requirement of hardcoding versions and dealing with conflicts of repo contributors using different OS/architectures.

**Comment by mildwonkey** [comment]
The guide is missing an important detail: to use a non-registry (or any non-hashicorp) provider, the configuration MUST include a terraform.required_providers block with the provider's source:

```hcl
terraform {
  required_providers {
    hashicups = {
      source = "hashicorp.com/edu/hashicups"
    }
  }
}
```

The source corresponds directly to the installation directory. When terraform finds the provider locally, it will not query the registry.

**Comment by mildwonkey** [comment]
And [here](https://www.terraform.io/docs/configuration/provider-requirements.html#in-house-providers) is the provider source documentation on terraform's website (the link is specifically to the local provider section).

**Comment by ShreyasNBS** [comment]
Hi @mildwonkey I have got my third party provider downloaded and setup under `terraform.d/plugins/github.com/atlassian/artifactory/2.0.0/linux_amd64/terraform-provider-artifactory` and my required providers section is setup as

`terraform {
  required_providers {
    artifactory = {
      source   = "github.com/atlassian/artifactory"
      versions = "2.0.0"
    }
  }
}`

However when tf init is run, I get this

`

Initializing provider plugins...
--
  | - Finding latest version of github.com/atlassian/artifactory...
  | - Finding latest version of hashicorp/aws...
  | - Finding latest version of hashicorp/artifactory...
  | - Installing github.com/atlassian/artifactory v2.0.0...
  | - Installed github.com/atlassian/artifactory v2.0.0 (unauthenticated)
  | - Installing hashicorp/aws v3.3.0...
  | - Installed hashicorp/aws v3.3.0 (signed by HashiCorp)
  |  
  | Error: Failed to install provider
  |  
  | Error while installing hashicorp/artifactory: provider registry
  | registry.terraform.io does not have a provider named
  | registry.terraform.io/hashicorp/artifactory
`

Any clue as to what I might be doing wrong? I suppose the only other option remaining for me is to place my provider under `registry.terraform.io/hashicorp/artifactory` and then get rid of the source argument as mentioned here [https://www.terraform.io/docs/configuration/provider-requirements.html#provider-installation](url) (checout the source addresses section, blue block)

**Comment by mildwonkey** [comment]
hi @ShreyasNBS , this is the repository for the hashicups provider. I recommend that you ask questions in the terraform [community forums](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!

**Comment by ShreyasNBS** [comment]
Apologies. I only meant to ask because I was following the exact same setup and it does not work. I will post the question there.

**Comment by ShreyasNBS** [comment]
Just an update. I solved it. It turns out that each module needs a required_providers section. More info here [https://github.com/hashicorp/terraform/issues/25984](url)

**Comment by remilapeyre** [comment]
@mildwonkey, thanks for the feedback :) When developing a provider, I think it's a bit weird having to choose a version and put the provider with all its other production ready versions. I could easily forget that I put it there and use it instead of the official version when I am done testing and back to writing production Terraform code. Would it be possible to make Terraform check the current working directory for the provider? This way I could do `go build ./...` and `rm terraform-provider-hashicups` when testing a provider instead, I'm open to anything else too, I would just like to have something simpler.

**Comment by mildwonkey** [comment]
Hi @remilapeyre That's not possible anymore @remilapeyre because terraform can no longer identify a provider with only the binary name: you could have two entirely different providers with the same binary name but different source addresses: https://www.terraform.io/docs/configuration/provider-requirements.html

A tip for provider developers is to create a symlink from the binary that's created by `go build` to where terraform expects to find the binary. It's an extra step up-front but enables you to rebuild the binary as necessary without copying it into place again. 

Again, please, if you have a general terraform question, you ask in the [terraform community forums](https://discuss.hashicorp.com/c/terraform-core/27) so we don't clutter up this unrelated issue. Thanks!

**Comment by im2nguyen** [comment]
Hi all, the [guide](https://learn.hashicorp.com/tutorials/terraform/provider-use?in=terraform/providers) and the [example repo](https://github.com/hashicorp/terraform-provider-hashicups/blob/master/examples/main.tf#L1) should have been updated to reflect this issue.

Is there anything else that pertains to the HashiCups repo? If not, I'll close this issue.

---

If you have a general Terraform question, please ask in the [Terraform community forums](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!

**Comment by remilapeyre** [comment]
Thanks, it's clear now :)

**Comment by idealo-ricardo-band** [comment]
I still don't get it. Any way I try it, it doesn't work. The current state in the repo is also not functional.

There is no `versions` here. It should be `version`.

```terraform
terraform {
  required_providers {
    hashicups = {
      versions = "0.3.1"
      source = "hashicorp.com/edu/hashicups"
    }
  }
}
```

If I adapt that to my customer provider made using the tutorial it does this:

```
Initializing provider plugins...
- Finding mydomain.com/mynamespace/myprovider versions matching "0.0.1"...
- Finding latest version of hashicorp/mydomain...
```

Then it fails with:

```
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/mydomain: provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/mydomain
│ 
│ All modules should specify their required_providers so that external consumers will get the correct providers when using a module. To see which modules
│ are currently depending on hashicorp/mydomain, run the following command:
│     terraform providers
```

**Comment by AlexHelmutSonntag** [comment]
Hi @idealo-ricardo-band what is your GO version ? 

Make sure the current go version is not less than **1.16** and that it is also set in GOROOT env variable.
checking with ´go env´ you should be able to see the current active version. 

**GOVERSION="go1.20.3"**
**GOROOT="/usr/local/go"**
