### ISSUE TITLE
Using deprecated gpg import step in release workflow

### ISSUE THREAD

**Issue by aidanmelen** [hashicorp/terraform-provider-hashicups#65]
The reference to the DEPRECATED [hashicorp/ghaction-import-gpg@v2.1.0](https://github.com/hashicorp/ghaction-import-gpg) found [here](https://github.com/hashicorp/terraform-provider-hashicups/blob/main/.github/workflows/release.yml#L31) should be replaced with [crazy-max/ghaction-import-gpg@v5](https://github.com/crazy-max/ghaction-import-gpg)

**Comment by im2nguyen** [comment]
Closing because PR that addressed this was merged.
