### ISSUE TITLE
Use consistent import alias for `hashicups-client-go`

### ISSUE THREAD

**Issue by jar-b** [hashicorp/terraform-provider-hashicups#79]
Within the provider source some files omit an alias for `"github.com/hashicorp-demoapp/hashicups-client-go"`, while others use `hc`. Using a consistent convention across files could make the [custom provider tutorial](https://developer.hashicorp.com/terraform/tutorials/providers) a bit easier to follow.

One advantage of using the unaliased import is that editors which "import on save" will automatically add the correct import when a new section of code is copy/pasted. This doesn't happen when the copied code references an alias (`hc`) for an import that isn't present yet, and the import and alias must be added manually before the code will compile.

Examples of both styles included below.
---

`hashicups/provider.go` does not alias the import:
https://github.com/hashicorp/terraform-provider-hashicups/blob/4619ed8b54134e4c2f36f8961f210a1707f809d5/hashicups/provider.go#L6
https://github.com/hashicorp/terraform-provider-hashicups/blob/4619ed8b54134e4c2f36f8961f210a1707f809d5/hashicups/provider.go#L60

`hashicups/data_source_order.go` does:
https://github.com/hashicorp/terraform-provider-hashicups/blob/4619ed8b54134e4c2f36f8961f210a1707f809d5/hashicups/data_source_order.go#L7
https://github.com/hashicorp/terraform-provider-hashicups/blob/4619ed8b54134e4c2f36f8961f210a1707f809d5/hashicups/data_source_order.go#L61

For this file I had to manually add the import line and alias it to get the code to compile while following the tutorial. Alternatively, if I replace `hc` with `hashicups` in the copied code, VSCode automagically adds the import.

**Comment by judithpatudith** [comment]
Hi @jar-b good catch, and thank you for the suggestion! Now that the Plugin Framework is GA we're moving the SDK tutorials to maintenance mode and aren't planning on improving them any more, but thank you for the report! The Plugin Framework collection that will eventually someday replace this one is here https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework. Let me know if you have any questions!
